FROM python:alpine3.20

# Installation des paquets nécessaires pour scapy
RUN apk -U upgrade && \
    apk add --no-cache libpcap libpcap-dev gcc musl-dev libffi-dev nmap
RUN pip install scapy

# Copier le script d'attaque
#COPY attack.py /attack.py

# Lancer le script d'attaque
#CMD ["python", "/attack.py"]

