FROM python:alpine3.20

# Installation des paquets nécessaires pour scapy
RUN apk -U upgrade && \
    apk add --no-cache libpcap libpcap-dev gcc musl-dev libffi-dev nmap iproute2
RUN pip install scapy

COPY Demo/Dockerfiles/attaquant-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# Copier le script d'attaque
#COPY attack.py /attack.py

# Lancer le script d'attaque
#CMD ["python", "/attack.py"]

