FROM python:alpine3.20

# Installation des paquets nécessaires pour scapy
RUN apk -U upgrade && \
    apk add --no-cache libpcap libpcap-dev gcc musl-dev libffi-dev
RUN pip install scapy

# Copier le script de l'idps
#COPY idps.py /idps.py

# Lancer le script de détection
#CMD ["python", "/idps.py"]
