FROM python:alpine3.20

# Installation des paquets nécessaires pour scapy
RUN apk -U upgrade && \
    apk add --no-cache libpcap libpcap-dev gcc musl-dev libffi-dev
RUN pip install scapy

# Copier le script de détection d'attaques
#COPY cible.py /cible.py

# Lancer le script de détection
#CMD ["python", "/cible.py"]
