FROM python:alpine3.20

# Installation des paquets nécessaires pour scapy
RUN apk -U upgrade && \
    apk add --no-cache nmap iproute2 curl
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk -U add --no-cache hping3

COPY Demo/Dockerfiles/attaquant-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

# Copier le script d'attaque
#COPY attack.py /attack.py

# Lancer le script d'attaque
#CMD ["python", "/attack.py"]

