version: "3.8"
services:
  # Attaquant 1
  atk1:
    image: python:alpine3.20
    container_name: attaquant1
    command: sleep infinity
    networks:
      net_public:
        ipv4_address: 172.20.1.2
    restart: unless-stopped

  # IDPS
  idps:
    image: python:alpine3.20
    container_name: idps
    command: sleep infinity
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      net_public:
        ipv4_address: 172.20.1.3
      net_private:
        ipv4_address: 172.20.2.2
    restart: unless-stopped

  # Cible
  cible:
    image: python:alpine3.20
    container_name: cible
    command: sleep infinity
    networks:
      net_private:
        ipv4_address: 172.20.2.3
    restart: unless-stopped

  # Attaquant 2
  atk2:
    image: python:alpine3.20
    container_name: attaquant2
    command: sleep infinity
    networks:
      net_private:
        ipv4_address: 172.20.2.4
    restart: unless-stopped

  ids:
    image: python:alpine3.20
    container_name: ids
    command: sleep infinity
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      net_private:
        ipv4_address: 172.20.2.5
    # Network mode host obligatoire pour que la sonde puisse sniffer le réseau
    network_mode: host
    restart: unless-stopped

  # BDD d'alertes
  alert_db:
    image: mysql:5.7
    container_name: alert_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alert_db
    networks:
      net_private:
        ipv4_address: 172.20.2.10
    restart: unless-stopped

networks:
  net_public:
    driver: bridge
     ipam:
      config:
        - subnet: 172.20.1.0/24
  net_private:
    driver: bridge
     ipam:
      config:
        - subnet: 172.20.2.0/24
